### ISSUE TITLE
Possible to run two KVWorkers in one process?

### ISSUE THREAD

**Issue by javelinjs** [dmlc/ps-lite#52]
Hi Mu,

I'm trying to integrate MXNet with Spark (https://github.com/dmlc/mxnet/issues/1637), while I found that it was hard to test the application in spark-local mode. When I try to start two workers in one process (local[*] mode), the postoffice complains 
```
16/04/25 20:55:44 WARN TaskSetManager: Lost task 0.0 in stage 6.0 (TID 6, localhost): ml.dmlc.mxnet.MXNetError: [20:55:44] src/postoffice.cc:77: Check failed: (customers_.count(id)) == ((size_t)0) id 0 already exists
	at ml.dmlc.mxnet.Base$.checkCall(Base.scala:108)
	at ml.dmlc.mxnet.KVStore$.create(KVStore.scala:26)
	at ml.dmlc.mxnet.spark.MXNet$$anonfun$main$2.apply(MXNet.scala:69)
	at ml.dmlc.mxnet.spark.MXNet$$anonfun$main$2.apply(MXNet.scala:55)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

So I wonder whether it is possible to have two customers (with same app_id) in one process?

@mli @tqchen

**Comment by tqchen** [comment]
This is a problem I found at rabit as well. This is related to the use of global singleton, as opposed to a specific created handle in kvstore. 

The question is to enable creation of multiple kvstore server, or worker instance by running mulitple devices. This can be resolved by change every usage of global singleton to runtime created handle.

I guess ps-lite itself might need some change, as well as mxnet's kvstore creation code in distributed setting. In general it should be doable.

**Comment by tqchen** [comment]
For rabit, what we did is simply make rabit runtime thread-local, so each thread see a different runtime. It might not be the right solution here(but might be a quick option), as mxnet is used to multi-threaded setting.

**Comment by tqchen** [comment]
We might also face similar problem due to mxnet's extensively use of the singleton to manage GPU resources.

As it might not be a good idea to place two workers with same GPU. @javelinjs We might need to find a way to make sure each worker get one unique resources and launched from separate process

**Comment by javelinjs** [comment]
But it is hard to guarantee that there's only one task run in one spark executor (related to one jvm process). I'm not sure how to make it work if we cannot make two KVWorkers share one process.

**Comment by tqchen** [comment]
I agree. I am simply stating the principle of limited resource problem was a bit more complicated here. I guess we can make it work. There is no restriction on mxnet to not being able to used by multiple threads. but resource-wise, we might need to be careful to ensure each worker fully occupies a resource

**Comment by tqchen** [comment]
Let us first look into enable things on same thread, before think about efficiency issue. @javelinjs

**Comment by mli** [comment]
this is because ps-lite has a singleton engine, which assumes each instance will have a separate process. could it be a problem for mxnet? its engine is also singleton

**Comment by mli** [comment]
this problem can be solved by allowing multiple engines to be exists, each of which binds a different network port.
